[package]
name = "thread-object-sharing"
version = "0.1.0"
authors = ["The wasm-bindgen Developers"]
edition = "2021"
rust-version = "1.56"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.87"
