#![allow(unused_imports)]
use super::*;
use wasm_bindgen::prelude::*;
#[wasm_bindgen]
extern "C" {
    # [wasm_bindgen (extends = :: js_sys :: Object , js_name = WebTransportDatagramDuplexStream , typescript_type = "WebTransportDatagramDuplexStream")]
    #[derive(Debug, Clone, PartialEq, Eq)]
    #[doc = "The `WebTransportDatagramDuplexStream` class."]
    #[doc = ""]
    #[doc = "[MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/WebTransportDatagramDuplexStream)"]
    #[doc = ""]
    #[doc = "*This API requires the following crate features to be activated: `WebTransportDatagramDuplexStream`*"]
    pub type WebTransportDatagramDuplexStream;
    #[cfg(feature = "ReadableStream")]
    # [wasm_bindgen (structural , method , getter , js_class = "WebTransportDatagramDuplexStream" , js_name = readable)]
    #[doc = "Getter for the `readable` field of this object."]
    #[doc = ""]
    #[doc = "[MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/WebTransportDatagramDuplexStream/readable)"]
    #[doc = ""]
    #[doc = "*This API requires the following crate features to be activated: `ReadableStream`, `WebTransportDatagramDuplexStream`*"]
    pub fn readable(this: &WebTransportDatagramDuplexStream) -> ReadableStream;
    #[cfg(feature = "WritableStream")]
    # [wasm_bindgen (structural , method , getter , js_class = "WebTransportDatagramDuplexStream" , js_name = writable)]
    #[doc = "Getter for the `writable` field of this object."]
    #[doc = ""]
    #[doc = "[MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/WebTransportDatagramDuplexStream/writable)"]
    #[doc = ""]
    #[doc = "*This API requires the following crate features to be activated: `WebTransportDatagramDuplexStream`, `WritableStream`*"]
    pub fn writable(this: &WebTransportDatagramDuplexStream) -> WritableStream;
    # [wasm_bindgen (structural , method , getter , js_class = "WebTransportDatagramDuplexStream" , js_name = maxDatagramSize)]
    #[doc = "Getter for the `maxDatagramSize` field of this object."]
    #[doc = ""]
    #[doc = "[MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/WebTransportDatagramDuplexStream/maxDatagramSize)"]
    #[doc = ""]
    #[doc = "*This API requires the following crate features to be activated: `WebTransportDatagramDuplexStream`*"]
    pub fn max_datagram_size(this: &WebTransportDatagramDuplexStream) -> u32;
    # [wasm_bindgen (structural , method , getter , js_class = "WebTransportDatagramDuplexStream" , js_name = incomingMaxAge)]
    #[doc = "Getter for the `incomingMaxAge` field of this object."]
    #[doc = ""]
    #[doc = "[MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/WebTransportDatagramDuplexStream/incomingMaxAge)"]
    #[doc = ""]
    #[doc = "*This API requires the following crate features to be activated: `WebTransportDatagramDuplexStream`*"]
    pub fn incoming_max_age(this: &WebTransportDatagramDuplexStream) -> Option<f64>;
    # [wasm_bindgen (structural , method , setter , js_class = "WebTransportDatagramDuplexStream" , js_name = incomingMaxAge)]
    #[doc = "Setter for the `incomingMaxAge` field of this object."]
    #[doc = ""]
    #[doc = "[MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/WebTransportDatagramDuplexStream/incomingMaxAge)"]
    #[doc = ""]
    #[doc = "*This API requires the following crate features to be activated: `WebTransportDatagramDuplexStream`*"]
    pub fn set_incoming_max_age(this: &WebTransportDatagramDuplexStream, value: Option<f64>);
    # [wasm_bindgen (structural , method , getter , js_class = "WebTransportDatagramDuplexStream" , js_name = outgoingMaxAge)]
    #[doc = "Getter for the `outgoingMaxAge` field of this object."]
    #[doc = ""]
    #[doc = "[MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/WebTransportDatagramDuplexStream/outgoingMaxAge)"]
    #[doc = ""]
    #[doc = "*This API requires the following crate features to be activated: `WebTransportDatagramDuplexStream`*"]
    pub fn outgoing_max_age(this: &WebTransportDatagramDuplexStream) -> Option<f64>;
    # [wasm_bindgen (structural , method , setter , js_class = "WebTransportDatagramDuplexStream" , js_name = outgoingMaxAge)]
    #[doc = "Setter for the `outgoingMaxAge` field of this object."]
    #[doc = ""]
    #[doc = "[MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/WebTransportDatagramDuplexStream/outgoingMaxAge)"]
    #[doc = ""]
    #[doc = "*This API requires the following crate features to be activated: `WebTransportDatagramDuplexStream`*"]
    pub fn set_outgoing_max_age(this: &WebTransportDatagramDuplexStream, value: Option<f64>);
    # [wasm_bindgen (structural , method , getter , js_class = "WebTransportDatagramDuplexStream" , js_name = incomingHighWaterMark)]
    #[doc = "Getter for the `incomingHighWaterMark` field of this object."]
    #[doc = ""]
    #[doc = "[MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/WebTransportDatagramDuplexStream/incomingHighWaterMark)"]
    #[doc = ""]
    #[doc = "*This API requires the following crate features to be activated: `WebTransportDatagramDuplexStream`*"]
    pub fn incoming_high_water_mark(this: &WebTransportDatagramDuplexStream) -> i32;
    # [wasm_bindgen (structural , method , setter , js_class = "WebTransportDatagramDuplexStream" , js_name = incomingHighWaterMark)]
    #[doc = "Setter for the `incomingHighWaterMark` field of this object."]
    #[doc = ""]
    #[doc = "[MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/WebTransportDatagramDuplexStream/incomingHighWaterMark)"]
    #[doc = ""]
    #[doc = "*This API requires the following crate features to be activated: `WebTransportDatagramDuplexStream`*"]
    pub fn set_incoming_high_water_mark(this: &WebTransportDatagramDuplexStream, value: i32);
    # [wasm_bindgen (structural , method , getter , js_class = "WebTransportDatagramDuplexStream" , js_name = outgoingHighWaterMark)]
    #[doc = "Getter for the `outgoingHighWaterMark` field of this object."]
    #[doc = ""]
    #[doc = "[MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/WebTransportDatagramDuplexStream/outgoingHighWaterMark)"]
    #[doc = ""]
    #[doc = "*This API requires the following crate features to be activated: `WebTransportDatagramDuplexStream`*"]
    pub fn outgoing_high_water_mark(this: &WebTransportDatagramDuplexStream) -> i32;
    # [wasm_bindgen (structural , method , setter , js_class = "WebTransportDatagramDuplexStream" , js_name = outgoingHighWaterMark)]
    #[doc = "Setter for the `outgoingHighWaterMark` field of this object."]
    #[doc = ""]
    #[doc = "[MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/WebTransportDatagramDuplexStream/outgoingHighWaterMark)"]
    #[doc = ""]
    #[doc = "*This API requires the following crate features to be activated: `WebTransportDatagramDuplexStream`*"]
    pub fn set_outgoing_high_water_mark(this: &WebTransportDatagramDuplexStream, value: i32);
}
