[package]
name = "build-web-sys"
version = "0.1.0"
authors = ["The wasm-bindgen Developers"]
license = "MIT/Apache-2.0"
categories = ["wasm"]
edition = "2018"

[dependencies]
env_logger = { version = "0.7.0", optional = true }
anyhow = "1.0"
sourcefile = "0.1"
wasm-bindgen-webidl = { path = "../../crates/webidl" }
