mod when_wasm_bindgen_test_runner_is_invoked_with_the_assembly;
mod when_wasm_bindgen_test_runner_is_invoked_without_arguments;

pub use when_wasm_bindgen_test_runner_is_invoked_with_the_assembly::*;
pub use when_wasm_bindgen_test_runner_is_invoked_without_arguments::*;
