(module
  (type (;0;) (func (result i32)))
  (type (;1;) (func (param i32)))
  (type (;2;) (func (param i32 i32 i32)))
  (type (;3;) (func (param i32 i32 i32 i32)))
  (func $foo (type 0) (result i32))
  (func $__wbindgen_exn_store (type 1) (param i32))
  (func $wasm_bindgen::convert::closures::invoke2_mut::he1784e4ef0648a5c (type 3) (param i32 i32 i32 i32))
  (func $<dyn_core::ops::function::FnMut<_A__>+Output_=_R_as_wasm_bindgen::closure::WasmClosure>::describe::invoke::h9da41a8dcaaa3ba0 (@name "<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h9da41a8dcaaa3ba0") (type 2) (param i32 i32 i32))
  (table (;0;) 78 78 funcref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "foo" (func $foo))
  (export "__wbindgen_export_0" (table 0))
  (export "_dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h9da41a8dcaaa3ba0" (func $<dyn_core::ops::function::FnMut<_A__>+Output_=_R_as_wasm_bindgen::closure::WasmClosure>::describe::invoke::h9da41a8dcaaa3ba0))
  (export "__wbindgen_exn_store" (func $__wbindgen_exn_store))
  (export "wasm_bindgen__convert__closures__invoke2_mut__he1784e4ef0648a5c" (func $wasm_bindgen::convert::closures::invoke2_mut::he1784e4ef0648a5c)))
