(module $reference_test.wasm
  (type (;0;) (func))
  (type (;1;) (func (param i32 i32)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;0;) (type 0)))
  (func $"<dyn core::ops::function::FnMut<()>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h08d04a92620849c7" (;1;) (type 1) (param i32 i32))
  (func $wasm_bindgen::convert::closures::invoke0::h0558a7c8fc0aaaa4 (;2;) (type 1) (param i32 i32))
  (func $exported (;3;) (type 0))
  (table (;0;) 37 37 funcref)
  (table (;1;) 128 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "exported" (func $exported))
  (export "__wbindgen_export_0" (table 0))
  (export "__wbindgen_export_1" (table 1))
  (export "_dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h08d04a92620849c7" (func $"<dyn core::ops::function::FnMut<()>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h08d04a92620849c7"))
  (export "wasm_bindgen__convert__closures__invoke0__h0558a7c8fc0aaaa4" (func $wasm_bindgen::convert::closures::invoke0::h0558a7c8fc0aaaa4))
  (export "__wbindgen_start" (func 0))
  (@custom "target_features" (after code) "\04+\0amultivalue+\0fmutable-globals+\0freference-types+\08sign-ext")
)

