(module $reference_test.wasm
  (type (;0;) (func))
  (type (;1;) (func (result i32)))
  (type (;2;) (func (param i32) (result i32)))
  (type (;3;) (func (param i32 i32)))
  (type (;4;) (func (param i32 i32) (result i32)))
  (type (;5;) (func (param i32 i32) (result i32 i32)))
  (type (;6;) (func (param i32 i32 i32)))
  (type (;7;) (func (param i32 i32 i32 i32) (result i32)))
  (type (;8;) (func (param i32 i64) (result i32 i64)))
  (type (;9;) (func (param i32 i64 i64) (result i32 i64 i64)))
  (type (;10;) (func (param i32 f64) (result i32 f64)))
  (type (;11;) (func (param i64) (result i64)))
  (type (;12;) (func (param i64 i64) (result i64 i64)))
  (type (;13;) (func (param f32) (result f32)))
  (type (;14;) (func (param f64) (result f64)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;0;) (type 0)))
  (func $__wbindgen_realloc (;1;) (type 7) (param i32 i32 i32 i32) (result i32))
  (func $__wbindgen_malloc (;2;) (type 4) (param i32 i32) (result i32))
  (func $__externref_drop_slice (;3;) (type 3) (param i32 i32))
  (func $echo_option_u8 (;4;) (type 2) (param i32) (result i32))
  (func $echo_option_i8 (;5;) (type 2) (param i32) (result i32))
  (func $echo_option_u16 (;6;) (type 2) (param i32) (result i32))
  (func $echo_option_i16 (;7;) (type 2) (param i32) (result i32))
  (func $echo_option_struct (;8;) (type 2) (param i32) (result i32))
  (func $echo_option_u32 (;9;) (type 14) (param f64) (result f64))
  (func $echo_option_i32 (;10;) (type 14) (param f64) (result f64))
  (func $echo_option_usize (;11;) (type 14) (param f64) (result f64))
  (func $echo_option_isize (;12;) (type 14) (param f64) (result f64))
  (func $echo_option_f32 (;13;) (type 14) (param f64) (result f64))
  (func $echo_u8 (;14;) (type 2) (param i32) (result i32))
  (func $echo_i8 (;15;) (type 2) (param i32) (result i32))
  (func $echo_u16 (;16;) (type 2) (param i32) (result i32))
  (func $echo_i16 (;17;) (type 2) (param i32) (result i32))
  (func $echo_u32 (;18;) (type 2) (param i32) (result i32))
  (func $echo_i32 (;19;) (type 2) (param i32) (result i32))
  (func $echo_usize (;20;) (type 2) (param i32) (result i32))
  (func $echo_isize (;21;) (type 2) (param i32) (result i32))
  (func $echo_f32 (;22;) (type 13) (param f32) (result f32))
  (func $echo_bool (;23;) (type 2) (param i32) (result i32))
  (func $echo_char (;24;) (type 2) (param i32) (result i32))
  (func $echo_struct (;25;) (type 2) (param i32) (result i32))
  (func $echo_option_bool (;26;) (type 2) (param i32) (result i32))
  (func $echo_option_char (;27;) (type 2) (param i32) (result i32))
  (func $echo_u64 (;28;) (type 11) (param i64) (result i64))
  (func $echo_i64 (;29;) (type 11) (param i64) (result i64))
  (func $echo_f64 (;30;) (type 14) (param f64) (result f64))
  (func $__wbindgen_free (;31;) (type 6) (param i32 i32 i32))
  (func $__wbg_foo_free (;32;) (type 3) (param i32 i32))
  (func $"echo_option_u128 multivalue shim" (;33;) (type 9) (param i32 i64 i64) (result i32 i64 i64))
  (func $"echo_option_i128 multivalue shim" (;34;) (type 9) (param i32 i64 i64) (result i32 i64 i64))
  (func $"echo_u128 multivalue shim" (;35;) (type 12) (param i64 i64) (result i64 i64))
  (func $"echo_i128 multivalue shim" (;36;) (type 12) (param i64 i64) (result i64 i64))
  (func $"echo_string multivalue shim" (;37;) (type 5) (param i32 i32) (result i32 i32))
  (func $"echo_vec_u8 multivalue shim" (;38;) (type 5) (param i32 i32) (result i32 i32))
  (func $"echo_vec_i8 multivalue shim" (;39;) (type 5) (param i32 i32) (result i32 i32))
  (func $"echo_vec_u16 multivalue shim" (;40;) (type 5) (param i32 i32) (result i32 i32))
  (func $"echo_vec_i16 multivalue shim" (;41;) (type 5) (param i32 i32) (result i32 i32))
  (func $"echo_vec_u32 multivalue shim" (;42;) (type 5) (param i32 i32) (result i32 i32))
  (func $"echo_vec_i32 multivalue shim" (;43;) (type 5) (param i32 i32) (result i32 i32))
  (func $"echo_vec_u64 multivalue shim" (;44;) (type 5) (param i32 i32) (result i32 i32))
  (func $"echo_vec_i64 multivalue shim" (;45;) (type 5) (param i32 i32) (result i32 i32))
  (func $"echo_vec_uninit_u8 multivalue shim" (;46;) (type 5) (param i32 i32) (result i32 i32))
  (func $"echo_vec_uninit_i8 multivalue shim" (;47;) (type 5) (param i32 i32) (result i32 i32))
  (func $"echo_vec_uninit_u16 multivalue shim" (;48;) (type 5) (param i32 i32) (result i32 i32))
  (func $"echo_vec_uninit_i16 multivalue shim" (;49;) (type 5) (param i32 i32) (result i32 i32))
  (func $"echo_vec_uninit_u32 multivalue shim" (;50;) (type 5) (param i32 i32) (result i32 i32))
  (func $"echo_vec_uninit_i32 multivalue shim" (;51;) (type 5) (param i32 i32) (result i32 i32))
  (func $"echo_vec_uninit_u64 multivalue shim" (;52;) (type 5) (param i32 i32) (result i32 i32))
  (func $"echo_vec_uninit_i64 multivalue shim" (;53;) (type 5) (param i32 i32) (result i32 i32))
  (func $"echo_vec_string multivalue shim" (;54;) (type 5) (param i32 i32) (result i32 i32))
  (func $"echo_vec_struct multivalue shim" (;55;) (type 5) (param i32 i32) (result i32 i32))
  (func $"echo_option_u64 multivalue shim" (;56;) (type 8) (param i32 i64) (result i32 i64))
  (func $"echo_option_i64 multivalue shim" (;57;) (type 8) (param i32 i64) (result i32 i64))
  (func $"echo_option_f64 multivalue shim" (;58;) (type 10) (param i32 f64) (result i32 f64))
  (func $"echo_option_string multivalue shim" (;59;) (type 5) (param i32 i32) (result i32 i32))
  (func $"echo_option_vec_u8 multivalue shim" (;60;) (type 5) (param i32 i32) (result i32 i32))
  (func $"echo_option_vec_i8 multivalue shim" (;61;) (type 5) (param i32 i32) (result i32 i32))
  (func $"echo_option_vec_u16 multivalue shim" (;62;) (type 5) (param i32 i32) (result i32 i32))
  (func $"echo_option_vec_i16 multivalue shim" (;63;) (type 5) (param i32 i32) (result i32 i32))
  (func $"echo_option_vec_u32 multivalue shim" (;64;) (type 5) (param i32 i32) (result i32 i32))
  (func $"echo_option_vec_i32 multivalue shim" (;65;) (type 5) (param i32 i32) (result i32 i32))
  (func $"echo_option_vec_u64 multivalue shim" (;66;) (type 5) (param i32 i32) (result i32 i32))
  (func $"echo_option_vec_i64 multivalue shim" (;67;) (type 5) (param i32 i32) (result i32 i32))
  (func $"echo_option_vec_uninit_u8 multivalue shim" (;68;) (type 5) (param i32 i32) (result i32 i32))
  (func $"echo_option_vec_uninit_i8 multivalue shim" (;69;) (type 5) (param i32 i32) (result i32 i32))
  (func $"echo_option_vec_uninit_u16 multivalue shim" (;70;) (type 5) (param i32 i32) (result i32 i32))
  (func $"echo_option_vec_uninit_i16 multivalue shim" (;71;) (type 5) (param i32 i32) (result i32 i32))
  (func $"echo_option_vec_uninit_u32 multivalue shim" (;72;) (type 5) (param i32 i32) (result i32 i32))
  (func $"echo_option_vec_uninit_i32 multivalue shim" (;73;) (type 5) (param i32 i32) (result i32 i32))
  (func $"echo_option_vec_uninit_u64 multivalue shim" (;74;) (type 5) (param i32 i32) (result i32 i32))
  (func $"echo_option_vec_uninit_i64 multivalue shim" (;75;) (type 5) (param i32 i32) (result i32 i32))
  (func $"echo_option_vec_string multivalue shim" (;76;) (type 5) (param i32 i32) (result i32 i32))
  (func $"echo_option_vec_struct multivalue shim" (;77;) (type 5) (param i32 i32) (result i32 i32))
  (func $__externref_table_alloc (;78;) (type 1) (result i32))
  (table (;0;) 128 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "__wbg_foo_free" (func $__wbg_foo_free))
  (export "echo_u8" (func $echo_u8))
  (export "echo_i8" (func $echo_i8))
  (export "echo_u16" (func $echo_u16))
  (export "echo_i16" (func $echo_i16))
  (export "echo_u32" (func $echo_u32))
  (export "echo_i32" (func $echo_i32))
  (export "echo_u64" (func $echo_u64))
  (export "echo_i64" (func $echo_i64))
  (export "echo_u128" (func $"echo_u128 multivalue shim"))
  (export "echo_i128" (func $"echo_i128 multivalue shim"))
  (export "echo_usize" (func $echo_usize))
  (export "echo_isize" (func $echo_isize))
  (export "echo_f32" (func $echo_f32))
  (export "echo_f64" (func $echo_f64))
  (export "echo_bool" (func $echo_bool))
  (export "echo_char" (func $echo_char))
  (export "echo_string" (func $"echo_string multivalue shim"))
  (export "echo_vec_u8" (func $"echo_vec_u8 multivalue shim"))
  (export "echo_vec_i8" (func $"echo_vec_i8 multivalue shim"))
  (export "echo_vec_u16" (func $"echo_vec_u16 multivalue shim"))
  (export "echo_vec_i16" (func $"echo_vec_i16 multivalue shim"))
  (export "echo_vec_u32" (func $"echo_vec_u32 multivalue shim"))
  (export "echo_vec_i32" (func $"echo_vec_i32 multivalue shim"))
  (export "echo_vec_u64" (func $"echo_vec_u64 multivalue shim"))
  (export "echo_vec_i64" (func $"echo_vec_i64 multivalue shim"))
  (export "echo_vec_uninit_u8" (func $"echo_vec_uninit_u8 multivalue shim"))
  (export "echo_vec_uninit_i8" (func $"echo_vec_uninit_i8 multivalue shim"))
  (export "echo_vec_uninit_u16" (func $"echo_vec_uninit_u16 multivalue shim"))
  (export "echo_vec_uninit_i16" (func $"echo_vec_uninit_i16 multivalue shim"))
  (export "echo_vec_uninit_u32" (func $"echo_vec_uninit_u32 multivalue shim"))
  (export "echo_vec_uninit_i32" (func $"echo_vec_uninit_i32 multivalue shim"))
  (export "echo_vec_uninit_u64" (func $"echo_vec_uninit_u64 multivalue shim"))
  (export "echo_vec_uninit_i64" (func $"echo_vec_uninit_i64 multivalue shim"))
  (export "echo_vec_string" (func $"echo_vec_string multivalue shim"))
  (export "echo_struct" (func $echo_struct))
  (export "echo_vec_struct" (func $"echo_vec_struct multivalue shim"))
  (export "echo_option_u8" (func $echo_option_u8))
  (export "echo_option_i8" (func $echo_option_i8))
  (export "echo_option_u16" (func $echo_option_u16))
  (export "echo_option_i16" (func $echo_option_i16))
  (export "echo_option_u32" (func $echo_option_u32))
  (export "echo_option_i32" (func $echo_option_i32))
  (export "echo_option_u64" (func $"echo_option_u64 multivalue shim"))
  (export "echo_option_i64" (func $"echo_option_i64 multivalue shim"))
  (export "echo_option_u128" (func $"echo_option_u128 multivalue shim"))
  (export "echo_option_i128" (func $"echo_option_i128 multivalue shim"))
  (export "echo_option_usize" (func $echo_option_usize))
  (export "echo_option_isize" (func $echo_option_isize))
  (export "echo_option_f32" (func $echo_option_f32))
  (export "echo_option_f64" (func $"echo_option_f64 multivalue shim"))
  (export "echo_option_bool" (func $echo_option_bool))
  (export "echo_option_char" (func $echo_option_char))
  (export "echo_option_string" (func $"echo_option_string multivalue shim"))
  (export "echo_option_vec_u8" (func $"echo_option_vec_u8 multivalue shim"))
  (export "echo_option_vec_i8" (func $"echo_option_vec_i8 multivalue shim"))
  (export "echo_option_vec_u16" (func $"echo_option_vec_u16 multivalue shim"))
  (export "echo_option_vec_i16" (func $"echo_option_vec_i16 multivalue shim"))
  (export "echo_option_vec_u32" (func $"echo_option_vec_u32 multivalue shim"))
  (export "echo_option_vec_i32" (func $"echo_option_vec_i32 multivalue shim"))
  (export "echo_option_vec_u64" (func $"echo_option_vec_u64 multivalue shim"))
  (export "echo_option_vec_i64" (func $"echo_option_vec_i64 multivalue shim"))
  (export "echo_option_vec_uninit_u8" (func $"echo_option_vec_uninit_u8 multivalue shim"))
  (export "echo_option_vec_uninit_i8" (func $"echo_option_vec_uninit_i8 multivalue shim"))
  (export "echo_option_vec_uninit_u16" (func $"echo_option_vec_uninit_u16 multivalue shim"))
  (export "echo_option_vec_uninit_i16" (func $"echo_option_vec_uninit_i16 multivalue shim"))
  (export "echo_option_vec_uninit_u32" (func $"echo_option_vec_uninit_u32 multivalue shim"))
  (export "echo_option_vec_uninit_i32" (func $"echo_option_vec_uninit_i32 multivalue shim"))
  (export "echo_option_vec_uninit_u64" (func $"echo_option_vec_uninit_u64 multivalue shim"))
  (export "echo_option_vec_uninit_i64" (func $"echo_option_vec_uninit_i64 multivalue shim"))
  (export "echo_option_vec_string" (func $"echo_option_vec_string multivalue shim"))
  (export "echo_option_struct" (func $echo_option_struct))
  (export "echo_option_vec_struct" (func $"echo_option_vec_struct multivalue shim"))
  (export "__wbindgen_malloc" (func $__wbindgen_malloc))
  (export "__wbindgen_realloc" (func $__wbindgen_realloc))
  (export "__wbindgen_export_2" (table 0))
  (export "__wbindgen_free" (func $__wbindgen_free))
  (export "__externref_table_alloc" (func $__externref_table_alloc))
  (export "__externref_drop_slice" (func $__externref_drop_slice))
  (export "__wbindgen_start" (func 0))
  (@custom "target_features" (after code) "\04+\0amultivalue+\0fmutable-globals+\0freference-types+\08sign-ext")
)

