(module $reference_test.wasm
  (type (;0;) (func (param i32) (result i32)))
  (type (;1;) (func (param i32 i32)))
  (type (;2;) (func (param i32 i32) (result i32)))
  (type (;3;) (func (param i32 i32 i32)))
  (type (;4;) (func (param i32 i32 i32 i32) (result i32)))
  (type (;5;) (func (param i32 i32 i64)))
  (type (;6;) (func (param i32 i32 f64)))
  (type (;7;) (func (param i64) (result i64)))
  (type (;8;) (func (param f32) (result f32)))
  (type (;9;) (func (param f64) (result f64)))
  (func $__wbindgen_realloc (;0;) (type 4) (param i32 i32 i32 i32) (result i32))
  (func $__wbindgen_malloc (;1;) (type 2) (param i32 i32) (result i32))
  (func $echo_option_u64 (;2;) (type 5) (param i32 i32 i64))
  (func $echo_option_i64 (;3;) (type 5) (param i32 i32 i64))
  (func $echo_option_f64 (;4;) (type 6) (param i32 i32 f64))
  (func $echo_string (;5;) (type 3) (param i32 i32 i32))
  (func $echo_vec_u8 (;6;) (type 3) (param i32 i32 i32))
  (func $echo_vec_struct (;7;) (type 3) (param i32 i32 i32))
  (func $echo_option_string (;8;) (type 3) (param i32 i32 i32))
  (func $echo_option_vec_u8 (;9;) (type 3) (param i32 i32 i32))
  (func $echo_option_vec_struct (;10;) (type 3) (param i32 i32 i32))
  (func $echo_option_u8 (;11;) (type 0) (param i32) (result i32))
  (func $echo_option_i8 (;12;) (type 0) (param i32) (result i32))
  (func $echo_option_u16 (;13;) (type 0) (param i32) (result i32))
  (func $echo_option_i16 (;14;) (type 0) (param i32) (result i32))
  (func $echo_option_struct (;15;) (type 0) (param i32) (result i32))
  (func $echo_option_u32 (;16;) (type 9) (param f64) (result f64))
  (func $echo_option_i32 (;17;) (type 9) (param f64) (result f64))
  (func $echo_option_usize (;18;) (type 9) (param f64) (result f64))
  (func $echo_option_isize (;19;) (type 9) (param f64) (result f64))
  (func $echo_option_f32 (;20;) (type 9) (param f64) (result f64))
  (func $echo_u8 (;21;) (type 0) (param i32) (result i32))
  (func $echo_i8 (;22;) (type 0) (param i32) (result i32))
  (func $echo_u16 (;23;) (type 0) (param i32) (result i32))
  (func $echo_i16 (;24;) (type 0) (param i32) (result i32))
  (func $echo_u32 (;25;) (type 0) (param i32) (result i32))
  (func $echo_i32 (;26;) (type 0) (param i32) (result i32))
  (func $echo_usize (;27;) (type 0) (param i32) (result i32))
  (func $echo_isize (;28;) (type 0) (param i32) (result i32))
  (func $echo_f32 (;29;) (type 8) (param f32) (result f32))
  (func $echo_bool (;30;) (type 0) (param i32) (result i32))
  (func $echo_char (;31;) (type 0) (param i32) (result i32))
  (func $echo_struct (;32;) (type 0) (param i32) (result i32))
  (func $echo_option_bool (;33;) (type 0) (param i32) (result i32))
  (func $echo_option_char (;34;) (type 0) (param i32) (result i32))
  (func $echo_u64 (;35;) (type 7) (param i64) (result i64))
  (func $echo_i64 (;36;) (type 7) (param i64) (result i64))
  (func $echo_f64 (;37;) (type 9) (param f64) (result f64))
  (func $__wbindgen_free (;38;) (type 3) (param i32 i32 i32))
  (func $__wbg_foo_free (;39;) (type 1) (param i32 i32))
  (func $__wbindgen_add_to_stack_pointer (;40;) (type 0) (param i32) (result i32))
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "__wbg_foo_free" (func $__wbg_foo_free))
  (export "echo_u8" (func $echo_u8))
  (export "echo_i8" (func $echo_i8))
  (export "echo_u16" (func $echo_u16))
  (export "echo_i16" (func $echo_i16))
  (export "echo_u32" (func $echo_u32))
  (export "echo_i32" (func $echo_i32))
  (export "echo_u64" (func $echo_u64))
  (export "echo_i64" (func $echo_i64))
  (export "echo_usize" (func $echo_usize))
  (export "echo_isize" (func $echo_isize))
  (export "echo_f32" (func $echo_f32))
  (export "echo_f64" (func $echo_f64))
  (export "echo_bool" (func $echo_bool))
  (export "echo_char" (func $echo_char))
  (export "echo_string" (func $echo_string))
  (export "echo_vec_u8" (func $echo_vec_u8))
  (export "echo_struct" (func $echo_struct))
  (export "echo_vec_struct" (func $echo_vec_struct))
  (export "echo_option_u8" (func $echo_option_u8))
  (export "echo_option_i8" (func $echo_option_i8))
  (export "echo_option_u16" (func $echo_option_u16))
  (export "echo_option_i16" (func $echo_option_i16))
  (export "echo_option_u32" (func $echo_option_u32))
  (export "echo_option_i32" (func $echo_option_i32))
  (export "echo_option_u64" (func $echo_option_u64))
  (export "echo_option_i64" (func $echo_option_i64))
  (export "echo_option_usize" (func $echo_option_usize))
  (export "echo_option_isize" (func $echo_option_isize))
  (export "echo_option_f32" (func $echo_option_f32))
  (export "echo_option_f64" (func $echo_option_f64))
  (export "echo_option_bool" (func $echo_option_bool))
  (export "echo_option_char" (func $echo_option_char))
  (export "echo_option_string" (func $echo_option_string))
  (export "echo_option_vec_u8" (func $echo_option_vec_u8))
  (export "echo_option_struct" (func $echo_option_struct))
  (export "echo_option_vec_struct" (func $echo_option_vec_struct))
  (export "__wbindgen_malloc" (func $__wbindgen_malloc))
  (export "__wbindgen_realloc" (func $__wbindgen_realloc))
  (export "__wbindgen_add_to_stack_pointer" (func $__wbindgen_add_to_stack_pointer))
  (export "__wbindgen_free" (func $__wbindgen_free))
  (@custom "target_features" (after code) "\02+\0fmutable-globals+\08sign-ext")
)

