(module $reference_test.wasm
  (type (;0;) (func))
  (type (;1;) (func (param i32) (result i32)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;0;) (type 0)))
  (func $enum_echo (;1;) (type 1) (param i32) (result i32))
  (func $option_enum_echo (;2;) (type 1) (param i32) (result i32))
  (func $get_name (;3;) (type 1) (param i32) (result i32))
  (func $option_string_enum_echo (;4;) (type 1) (param i32) (result i32))
  (func $option_order (;5;) (type 1) (param i32) (result i32))
  (table (;0;) 128 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "enum_echo" (func $enum_echo))
  (export "option_enum_echo" (func $option_enum_echo))
  (export "get_name" (func $get_name))
  (export "option_string_enum_echo" (func $option_string_enum_echo))
  (export "option_order" (func $option_order))
  (export "__wbindgen_export_0" (table 0))
  (export "__wbindgen_start" (func 0))
  (@custom "target_features" (after code) "\04+\0amultivalue+\0fmutable-globals+\0freference-types+\08sign-ext")
)

