(module $reference_test.wasm
  (type (;0;) (func (param i32) (result i32)))
  (type (;1;) (func (param i32 i32)))
  (type (;2;) (func (param i32 i32) (result i32)))
  (type (;3;) (func (param i32 i32 i32)))
  (type (;4;) (func (param i32 i32 i32) (result i32)))
  (func $fn_with_attr (;0;) (type 3) (param i32 i32 i32))
  (func $holdsnumber_method_with_attr (;1;) (type 4) (param i32 i32 i32) (result i32))
  (func $holdsnumber_get_inner (;2;) (type 0) (param i32) (result i32))
  (func $holdsnumber_static_fn_with_attr (;3;) (type 2) (param i32 i32) (result i32))
  (func $__wbg_holdsnumber_free (;4;) (type 1) (param i32 i32))
  (func $__wbindgen_add_to_stack_pointer (;5;) (type 0) (param i32) (result i32))
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "fn_with_attr" (func $fn_with_attr))
  (export "__wbg_holdsnumber_free" (func $__wbg_holdsnumber_free))
  (export "holdsnumber_get_inner" (func $holdsnumber_get_inner))
  (export "holdsnumber_static_fn_with_attr" (func $holdsnumber_static_fn_with_attr))
  (export "holdsnumber_method_with_attr" (func $holdsnumber_method_with_attr))
  (export "__wbindgen_add_to_stack_pointer" (func $__wbindgen_add_to_stack_pointer))
  (@custom "target_features" (after code) "\02+\0fmutable-globals+\08sign-ext")
)

