(module $reference_test.wasm
  (type (;0;) (func))
  (type (;1;) (func (result i32)))
  (type (;2;) (func (param i32)))
  (type (;3;) (func (param i32) (result i32)))
  (type (;4;) (func (param i32) (result f64)))
  (type (;5;) (func (param i32 i32)))
  (type (;6;) (func (param i32 i32) (result i32)))
  (type (;7;) (func (param i32 i32 i32)))
  (type (;8;) (func (param i32 i32 i32 i32) (result i32)))
  (type (;9;) (func (param i32 f64)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;0;) (type 0)))
  (func $__wbindgen_realloc (;1;) (type 8) (param i32 i32 i32 i32) (result i32))
  (func $__wbindgen_malloc (;2;) (type 6) (param i32 i32) (result i32))
  (func $foo_set_weird (;3;) (type 7) (param i32 i32 i32))
  (func $__wbg_set_foo_y (;4;) (type 9) (param i32 f64))
  (func $__wbg_get_foo_y (;5;) (type 4) (param i32) (result f64))
  (func $__wbg_get_foo_x (;6;) (type 3) (param i32) (result i32))
  (func $foo_set_z (;7;) (type 9) (param i32 f64))
  (func $foo_set_lone_setter (;8;) (type 9) (param i32 f64))
  (func $foo_z (;9;) (type 4) (param i32) (result f64))
  (func $foo_lone_getter (;10;) (type 4) (param i32) (result f64))
  (func $__wbg_set_foo_x (;11;) (type 5) (param i32 i32))
  (func $foo_weird (;12;) (type 3) (param i32) (result i32))
  (func $foo_x_static (;13;) (type 1) (result i32))
  (func $__wbg_foo_free (;14;) (type 5) (param i32 i32))
  (func $foo_set_x_static (;15;) (type 2) (param i32))
  (table (;0;) 128 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "__wbg_foo_free" (func $__wbg_foo_free))
  (export "__wbg_get_foo_x" (func $__wbg_get_foo_x))
  (export "__wbg_set_foo_x" (func $__wbg_set_foo_x))
  (export "__wbg_get_foo_y" (func $__wbg_get_foo_y))
  (export "__wbg_set_foo_y" (func $__wbg_set_foo_y))
  (export "foo_z" (func $foo_z))
  (export "foo_set_z" (func $foo_set_z))
  (export "foo_lone_getter" (func $foo_lone_getter))
  (export "foo_set_lone_setter" (func $foo_set_lone_setter))
  (export "foo_weird" (func $foo_weird))
  (export "foo_set_weird" (func $foo_set_weird))
  (export "foo_x_static" (func $foo_x_static))
  (export "foo_set_x_static" (func $foo_set_x_static))
  (export "__wbindgen_export_0" (table 0))
  (export "__wbindgen_malloc" (func $__wbindgen_malloc))
  (export "__wbindgen_realloc" (func $__wbindgen_realloc))
  (export "__wbindgen_start" (func 0))
  (@custom "target_features" (after code) "\04+\0amultivalue+\0fmutable-globals+\0freference-types+\08sign-ext")
)

