(module
  (type (;0;) (func))
  (type (;1;) (func (param i32)))
  (func $__wbindgen_exn_store (type 1) (param i32))
  (func $exported (type 0))
  (memory (;0;) 17)
  (global (;0;) i32 (i32.const 1051544))
  (export "memory" (memory 0))
  (export "__rustc_debug_gdb_scripts_section__" (global 0))
  (export "exported" (func $exported))
  (export "__wbindgen_exn_store" (func $__wbindgen_exn_store)))
