(module
  (type (;0;) (func (param i32)))
  (type (;1;) (func (param i32) (result i32)))
  (func $__wbindgen_exn_store (type 0) (param i32))
  (func $exported (type 0) (param i32))
  (func $__wbindgen_add_to_stack_pointer (type 1) (param i32) (result i32))
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "exported" (func $exported))
  (export "__wbindgen_exn_store" (func $__wbindgen_exn_store))
  (export "__wbindgen_add_to_stack_pointer" (func $__wbindgen_add_to_stack_pointer)))
