(module $reference_test.wasm
  (type (;0;) (func))
  (type (;1;) (func (result i32)))
  (type (;2;) (func (result i32 i32)))
  (type (;3;) (func (param i32)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;0;) (type 0)))
  (func $__wbindgen_exn_store (;1;) (type 3) (param i32))
  (func $__externref_table_dealloc (;2;) (type 3) (param i32))
  (func $"exported multivalue shim" (;3;) (type 2) (result i32 i32))
  (func $__externref_table_alloc (;4;) (type 1) (result i32))
  (table (;0;) 128 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "exported" (func $"exported multivalue shim"))
  (export "__wbindgen_exn_store" (func $__wbindgen_exn_store))
  (export "__externref_table_alloc" (func $__externref_table_alloc))
  (export "__wbindgen_export_2" (table 0))
  (export "__externref_table_dealloc" (func $__externref_table_dealloc))
  (export "__wbindgen_start" (func 0))
  (@custom "target_features" (after code) "\04+\0amultivalue+\0fmutable-globals+\0freference-types+\08sign-ext")
)

