(module
  (type (;0;) (func))
  (func $empty (type 0))
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "empty" (func $empty))
  (@interface type (;0;) (func))
  (@interface func (;0;) (type 0)
    call-core $empty)
  (@interface export "empty" (func 0)))
