(module $reference_test.wasm
  (type (;0;) (func))
  (type (;1;) (func (result i32)))
  (type (;2;) (func (result externref)))
  (import "wbg" "__wbindgen_init_externref_table" (func (;0;) (type 0)))
  (func $is_memory_shared (;1;) (type 1) (result i32))
  (func $"module_ externref shim" (;2;) (type 2) (result externref))
  (func $"exports externref shim" (;3;) (type 2) (result externref))
  (func $"memory_ externref shim" (;4;) (type 2) (result externref))
  (func $"function_table externref shim" (;5;) (type 2) (result externref))
  (table (;0;) 25 25 funcref)
  (table (;1;) 128 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "module_" (func $"module_ externref shim"))
  (export "exports" (func $"exports externref shim"))
  (export "memory_" (func $"memory_ externref shim"))
  (export "is_memory_shared" (func $is_memory_shared))
  (export "function_table" (func $"function_table externref shim"))
  (export "__wbindgen_export_0" (table 0))
  (export "__wbindgen_export_1" (table 1))
  (export "__wbindgen_start" (func 0))
  (@custom "target_features" (after code) "\04+\0amultivalue+\0fmutable-globals+\0freference-types+\08sign-ext")
)

