(module $reference_test.wasm
  (type (;0;) (func))
  (type (;1;) (func (param i32)))
  (type (;2;) (func (param i32) (result i32)))
  (type (;3;) (func (param i32 f64 f64 f64) (result i32)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;0;) (type 0)))
  (func $add (;1;) (type 3) (param i32 f64 f64 f64) (result i32))
  (func $docme (;2;) (type 2) (param i32) (result i32))
  (func $docme_skip (;3;) (type 2) (param i32) (result i32))
  (func $i_has_docs (;4;) (type 2) (param i32) (result i32))
  (func $indent_test1 (;5;) (type 1) (param i32))
  (func $indent_test2 (;6;) (type 1) (param i32))
  (table (;0;) 128 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "docme" (func $docme))
  (export "docme_skip" (func $docme_skip))
  (export "i_has_docs" (func $i_has_docs))
  (export "add" (func $add))
  (export "indent_test1" (func $indent_test1))
  (export "indent_test2" (func $indent_test2))
  (export "__wbindgen_export_0" (table 0))
  (export "__wbindgen_start" (func 0))
  (@custom "target_features" (after code) "\04+\0amultivalue+\0fmutable-globals+\0freference-types+\08sign-ext")
)

