(module $reference_test.wasm
  (type (;0;) (func))
  (type (;1;) (func (result i32)))
  (type (;2;) (func (param i32 i32)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;0;) (type 0)))
  (func $weird_arguments (;1;) (type 2) (param i32 i32))
  (func $__wbg_class_free (;2;) (type 2) (param i32 i32))
  (func $class_new (;3;) (type 1) (result i32))
  (func $exported (;4;) (type 0))
  (func $_function (;5;) (type 0))
  (func $_var (;6;) (type 0))
  (table (;0;) 128 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "exported" (func $exported))
  (export "_function" (func $_function))
  (export "_var" (func $_var))
  (export "weird_arguments" (func $weird_arguments))
  (export "__wbg_class_free" (func $__wbg_class_free))
  (export "class_new" (func $class_new))
  (export "__wbindgen_export_0" (table 0))
  (export "__wbindgen_start" (func 0))
  (@custom "target_features" (after code) "\04+\0amultivalue+\0fmutable-globals+\0freference-types+\08sign-ext")
)

