(module $reference_test.wasm
  (type (;0;) (func (param i32) (result i32)))
  (type (;1;) (func (param i32 i32) (result i32)))
  (type (;2;) (func (param i32 i32 i32 i32) (result i32)))
  (func $__wbindgen_realloc (;0;) (type 2) (param i32 i32 i32 i32) (result i32))
  (func $__wbindgen_malloc (;1;) (type 1) (param i32 i32) (result i32))
  (func $imageformat_from_str (;2;) (type 1) (param i32 i32) (result i32))
  (func $status_from_bool (;3;) (type 0) (param i32) (result i32))
  (func $imageformat_is_lossless (;4;) (type 0) (param i32) (result i32))
  (func $status_to_bool (;5;) (type 0) (param i32) (result i32))
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "imageformat_from_str" (func $imageformat_from_str))
  (export "imageformat_is_lossless" (func $imageformat_is_lossless))
  (export "status_from_bool" (func $status_from_bool))
  (export "status_to_bool" (func $status_to_bool))
  (export "__wbindgen_malloc" (func $__wbindgen_malloc))
  (export "__wbindgen_realloc" (func $__wbindgen_realloc))
  (@custom "target_features" (after code) "\04+\0amultivalue+\0fmutable-globals+\0freference-types+\08sign-ext")
)

