(module $reference_test.wasm
  (type (;0;) (func))
  (type (;1;) (func (param i32) (result i32)))
  (type (;2;) (func (param i32 i32) (result i32)))
  (type (;3;) (func (param i32 i32 i32 i32) (result i32)))
  (import "__wbindgen_placeholder__" "__wbindgen_init_externref_table" (func (;0;) (type 0)))
  (func $__wbindgen_realloc (;1;) (type 3) (param i32 i32 i32 i32) (result i32))
  (func $__wbindgen_malloc (;2;) (type 2) (param i32 i32) (result i32))
  (func $imageformat_from_str (;3;) (type 2) (param i32 i32) (result i32))
  (func $status_from_bool (;4;) (type 1) (param i32) (result i32))
  (func $imageformat_is_lossless (;5;) (type 1) (param i32) (result i32))
  (func $status_to_bool (;6;) (type 1) (param i32) (result i32))
  (table (;0;) 128 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "imageformat_from_str" (func $imageformat_from_str))
  (export "imageformat_is_lossless" (func $imageformat_is_lossless))
  (export "status_from_bool" (func $status_from_bool))
  (export "status_to_bool" (func $status_to_bool))
  (export "__wbindgen_export_0" (table 0))
  (export "__wbindgen_malloc" (func $__wbindgen_malloc))
  (export "__wbindgen_realloc" (func $__wbindgen_realloc))
  (export "__wbindgen_start" (func 0))
  (@custom "target_features" (after code) "\04+\0amultivalue+\0fmutable-globals+\0freference-types+\08sign-ext")
)

