(module $reference_test.wasm
  (type (;0;) (func))
  (type (;1;) (func (param f64 i32 f64)))
  (type (;2;) (func (param f64 f64 f64)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;0;) (type 0)))
  (func $all_optional (;1;) (type 2) (param f64 f64 f64))
  (func $some_optional (;2;) (type 1) (param f64 i32 f64))
  (table (;0;) 128 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "all_optional" (func $all_optional))
  (export "some_optional" (func $some_optional))
  (export "__wbindgen_export_0" (table 0))
  (export "__wbindgen_start" (func 0))
  (@custom "target_features" (after code) "\04+\0amultivalue+\0fmutable-globals+\0freference-types+\08sign-ext")
)

