(module $reference_test.wasm
  (type (;0;) (func (param i32) (result i32)))
  (type (;1;) (func (param i32 i32)))
  (func $test_test2 (;0;) (type 1) (param i32 i32))
  (func $test1 (;1;) (type 0) (param i32) (result i32))
  (func $test_test1 (;2;) (type 0) (param i32) (result i32))
  (func $__wbg_test_free (;3;) (type 1) (param i32 i32))
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "test1" (func $test1))
  (export "__wbg_test_free" (func $__wbg_test_free))
  (export "test_test1" (func $test_test1))
  (export "test_test2" (func $test_test2))
  (@custom "target_features" (after code) "\02+\0fmutable-globals+\08sign-ext")
)

