(module $reference_test.wasm
  (type (;0;) (func))
  (type (;1;) (func (param i32) (result i32)))
  (type (;2;) (func (param i32 i32)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;0;) (type 0)))
  (func $test_test2 (;1;) (type 2) (param i32 i32))
  (func $test1 (;2;) (type 1) (param i32) (result i32))
  (func $test_test1 (;3;) (type 1) (param i32) (result i32))
  (func $__wbg_test_free (;4;) (type 2) (param i32 i32))
  (table (;0;) 128 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "test1" (func $test1))
  (export "__wbg_test_free" (func $__wbg_test_free))
  (export "test_test1" (func $test_test1))
  (export "test_test2" (func $test_test2))
  (export "__wbindgen_export_0" (table 0))
  (export "__wbindgen_start" (func 0))
  (@custom "target_features" (after code) "\04+\0amultivalue+\0fmutable-globals+\0freference-types+\08sign-ext")
)

