(module $reference_test.wasm
  (type (;0;) (func))
  (type (;1;) (func (param i32) (result i32)))
  (type (;2;) (func (param i32 i32)))
  (type (;3;) (func (param i32 f64)))
  (func $__wbg_get_ruststruct_foo (;0;) (type 1) (param i32) (result i32))
  (func $__wbg_get_ruststruct_someCoolField (;1;) (type 1) (param i32) (result i32))
  (func $__wbg_get_ruststruct_another_field_for_you (;2;) (type 1) (param i32) (result i32))
  (func $ruststruct_incrementFoo (;3;) (type 3) (param i32 f64))
  (func $__wbg_set_ruststruct_foo (;4;) (type 2) (param i32 i32))
  (func $__wbg_set_ruststruct_someCoolField (;5;) (type 2) (param i32 i32))
  (func $__wbg_set_ruststruct_another_field_for_you (;6;) (type 2) (param i32 i32))
  (func $ruststruct_get_another (;7;) (type 1) (param i32) (result i32))
  (func $ruststruct_setFoo (;8;) (type 2) (param i32 i32))
  (func $export_from_rust (;9;) (type 1) (param i32) (result i32))
  (func $__wbg_ruststruct_free (;10;) (type 2) (param i32 i32))
  (func $ruststruct_i_dont_get_renamed (;11;) (type 0))
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "export_from_rust" (func $export_from_rust))
  (export "__wbg_ruststruct_free" (func $__wbg_ruststruct_free))
  (export "__wbg_get_ruststruct_foo" (func $__wbg_get_ruststruct_foo))
  (export "__wbg_set_ruststruct_foo" (func $__wbg_set_ruststruct_foo))
  (export "__wbg_get_ruststruct_someCoolField" (func $__wbg_get_ruststruct_someCoolField))
  (export "__wbg_set_ruststruct_someCoolField" (func $__wbg_set_ruststruct_someCoolField))
  (export "__wbg_get_ruststruct_another_field_for_you" (func $__wbg_get_ruststruct_another_field_for_you))
  (export "__wbg_set_ruststruct_another_field_for_you" (func $__wbg_set_ruststruct_another_field_for_you))
  (export "ruststruct_i_dont_get_renamed" (func $ruststruct_i_dont_get_renamed))
  (export "ruststruct_incrementFoo" (func $ruststruct_incrementFoo))
  (export "ruststruct_setFoo" (func $ruststruct_setFoo))
  (export "ruststruct_get_another" (func $ruststruct_get_another))
  (@custom "target_features" (after code) "\02+\0fmutable-globals+\08sign-ext")
)

