(module $reference_test.wasm
  (type (;0;) (func))
  (type (;1;) (func (result i32)))
  (type (;2;) (func (param i32)))
  (type (;3;) (func (param i32) (result i32)))
  (type (;4;) (func (param i32 i32)))
  (type (;5;) (func (param i32 f64)))
  (func $__wbg_get_ruststruct_foo (;0;) (type 3) (param i32) (result i32))
  (func $__wbg_get_ruststruct_someCoolField (;1;) (type 3) (param i32) (result i32))
  (func $__wbg_get_ruststruct_another_field_for_you (;2;) (type 3) (param i32) (result i32))
  (func $ruststruct_incrementFoo (;3;) (type 5) (param i32 f64))
  (func $__wbg_set_ruststruct_foo (;4;) (type 4) (param i32 i32))
  (func $__wbg_set_ruststruct_someCoolField (;5;) (type 4) (param i32 i32))
  (func $__wbg_set_ruststruct_another_field_for_you (;6;) (type 4) (param i32 i32))
  (func $ruststruct_get_another (;7;) (type 3) (param i32) (result i32))
  (func $ruststruct_someOtherProp (;8;) (type 3) (param i32) (result i32))
  (func $ruststruct_someDifferentProp (;9;) (type 3) (param i32) (result i32))
  (func $ruststruct_my_unique_name (;10;) (type 3) (param i32) (result i32))
  (func $ruststruct_setFoo (;11;) (type 4) (param i32 i32))
  (func $ruststruct_set_someOtherProp (;12;) (type 4) (param i32 i32))
  (func $ruststruct_set_someDifferentProp (;13;) (type 4) (param i32 i32))
  (func $ruststruct_set_my_unique_name (;14;) (type 4) (param i32 i32))
  (func $export_from_rust (;15;) (type 3) (param i32) (result i32))
  (func $__wbg_ruststruct_free (;16;) (type 4) (param i32 i32))
  (func $ruststruct_someStaticProp (;17;) (type 1) (result i32))
  (func $ruststruct_staticMethod (;18;) (type 2) (param i32))
  (func $ruststruct_IHaveA_funky_name (;19;) (type 2) (param i32))
  (func $ruststruct_set_someStaticProp (;20;) (type 2) (param i32))
  (func $ruststruct_i_dont_get_renamed (;21;) (type 0))
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "export_from_rust" (func $export_from_rust))
  (export "__wbg_ruststruct_free" (func $__wbg_ruststruct_free))
  (export "__wbg_get_ruststruct_foo" (func $__wbg_get_ruststruct_foo))
  (export "__wbg_set_ruststruct_foo" (func $__wbg_set_ruststruct_foo))
  (export "__wbg_get_ruststruct_someCoolField" (func $__wbg_get_ruststruct_someCoolField))
  (export "__wbg_set_ruststruct_someCoolField" (func $__wbg_set_ruststruct_someCoolField))
  (export "__wbg_get_ruststruct_another_field_for_you" (func $__wbg_get_ruststruct_another_field_for_you))
  (export "__wbg_set_ruststruct_another_field_for_you" (func $__wbg_set_ruststruct_another_field_for_you))
  (export "ruststruct_i_dont_get_renamed" (func $ruststruct_i_dont_get_renamed))
  (export "ruststruct_incrementFoo" (func $ruststruct_incrementFoo))
  (export "ruststruct_setFoo" (func $ruststruct_setFoo))
  (export "ruststruct_get_another" (func $ruststruct_get_another))
  (export "ruststruct_staticMethod" (func $ruststruct_staticMethod))
  (export "ruststruct_IHaveA_funky_name" (func $ruststruct_IHaveA_funky_name))
  (export "ruststruct_someOtherProp" (func $ruststruct_someOtherProp))
  (export "ruststruct_set_someOtherProp" (func $ruststruct_set_someOtherProp))
  (export "ruststruct_someDifferentProp" (func $ruststruct_someDifferentProp))
  (export "ruststruct_set_someDifferentProp" (func $ruststruct_set_someDifferentProp))
  (export "ruststruct_my_unique_name" (func $ruststruct_my_unique_name))
  (export "ruststruct_set_my_unique_name" (func $ruststruct_set_my_unique_name))
  (export "ruststruct_someStaticProp" (func $ruststruct_someStaticProp))
  (export "ruststruct_set_someStaticProp" (func $ruststruct_set_someStaticProp))
  (@custom "target_features" (after code) "\04+\0amultivalue+\0fmutable-globals+\0freference-types+\08sign-ext")
)

