(module $reference_test.wasm
  (type (;0;) (func))
  (type (;1;) (func (result i32)))
  (type (;2;) (func (param i32)))
  (type (;3;) (func (param i32 i32)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;0;) (type 0)))
  (func $test_ref_self (;1;) (type 2) (param i32))
  (func $test_ref_mut_self (;2;) (type 2) (param i32))
  (func $test_self_ref_Self (;3;) (type 2) (param i32))
  (func $test_self_ref_mut_Self (;4;) (type 2) (param i32))
  (func $__wbg_test_free (;5;) (type 3) (param i32 i32))
  (func $test_new (;6;) (type 1) (result i32))
  (func $test_consume_self (;7;) (type 2) (param i32))
  (func $test_self_Self (;8;) (type 2) (param i32))
  (table (;0;) 128 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "__wbg_test_free" (func $__wbg_test_free))
  (export "test_new" (func $test_new))
  (export "test_consume_self" (func $test_consume_self))
  (export "test_ref_self" (func $test_ref_self))
  (export "test_ref_mut_self" (func $test_ref_mut_self))
  (export "test_self_Self" (func $test_self_Self))
  (export "test_self_ref_Self" (func $test_self_ref_Self))
  (export "test_self_ref_mut_Self" (func $test_self_ref_mut_Self))
  (export "__wbindgen_export_0" (table 0))
  (export "__wbindgen_start" (func 0))
  (@custom "target_features" (after code) "\04+\0amultivalue+\0fmutable-globals+\0freference-types+\08sign-ext")
)

