(module $reference_test.wasm
  (type (;0;) (func (result i32)))
  (type (;1;) (func (param i32)))
  (type (;2;) (func (param i32 i32)))
  (func $test_ref_self (;0;) (type 1) (param i32))
  (func $test_ref_mut_self (;1;) (type 1) (param i32))
  (func $test_self_ref_Self (;2;) (type 1) (param i32))
  (func $test_self_ref_mut_Self (;3;) (type 1) (param i32))
  (func $__wbg_test_free (;4;) (type 2) (param i32 i32))
  (func $test_new (;5;) (type 0) (result i32))
  (func $test_consume_self (;6;) (type 1) (param i32))
  (func $test_self_Self (;7;) (type 1) (param i32))
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "__wbg_test_free" (func $__wbg_test_free))
  (export "test_new" (func $test_new))
  (export "test_consume_self" (func $test_consume_self))
  (export "test_ref_self" (func $test_ref_self))
  (export "test_ref_mut_self" (func $test_ref_mut_self))
  (export "test_self_Self" (func $test_self_Self))
  (export "test_self_ref_Self" (func $test_self_ref_Self))
  (export "test_self_ref_mut_Self" (func $test_self_ref_mut_Self))
  (@custom "target_features" (after code) "\02+\0fmutable-globals+\08sign-ext")
)

