(module $reference_test.wasm
  (type (;0;) (func (param i32) (result i32)))
  (type (;1;) (func (param i32 i32)))
  (type (;2;) (func (param i32 i32) (result i32)))
  (type (;3;) (func (param i32 i32 i32)))
  (type (;4;) (func (param i32 i32 i32 i32) (result i32)))
  (func $__wbindgen_realloc (;0;) (type 4) (param i32 i32 i32 i32) (result i32))
  (func $__wbindgen_malloc (;1;) (type 2) (param i32 i32) (result i32))
  (func $foo_Symbol_toPrimitive (;2;) (type 1) (param i32 i32))
  (func $foo_to_string_tag (;3;) (type 1) (param i32 i32))
  (func $__wbindgen_free (;4;) (type 3) (param i32 i32 i32))
  (func $__wbg_foo_free (;5;) (type 1) (param i32 i32))
  (func $__wbindgen_add_to_stack_pointer (;6;) (type 0) (param i32) (result i32))
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "__wbg_foo_free" (func $__wbg_foo_free))
  (export "foo_Symbol_toPrimitive" (func $foo_Symbol_toPrimitive))
  (export "foo_to_string_tag" (func $foo_to_string_tag))
  (export "__wbindgen_malloc" (func $__wbindgen_malloc))
  (export "__wbindgen_realloc" (func $__wbindgen_realloc))
  (export "__wbindgen_add_to_stack_pointer" (func $__wbindgen_add_to_stack_pointer))
  (export "__wbindgen_free" (func $__wbindgen_free))
  (@custom "target_features" (after code) "\02+\0fmutable-globals+\08sign-ext")
)

