(module $reference_test.wasm
  (type (;0;) (func))
  (type (;1;) (func (result i32)))
  (type (;2;) (func (param i32 i32)))
  (type (;3;) (func (param i32 i32) (result i32)))
  (type (;4;) (func (param externref)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;0;) (type 0)))
  (func $__wbindgen_malloc (;1;) (type 3) (param i32 i32) (result i32))
  (func $slice (;2;) (type 2) (param i32 i32))
  (func $__externref_table_alloc (;3;) (type 1) (result i32))
  (func $"single externref shim" (;4;) (type 4) (param externref))
  (table (;0;) 128 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "single" (func $"single externref shim"))
  (export "slice" (func $slice))
  (export "__wbindgen_export_0" (table 0))
  (export "__externref_table_alloc" (func $__externref_table_alloc))
  (export "__wbindgen_malloc" (func $__wbindgen_malloc))
  (export "__wbindgen_start" (func 0))
  (@custom "target_features" (after code) "\04+\0amultivalue+\0fmutable-globals+\0freference-types+\08sign-ext")
)

