(module $reference_test.wasm
  (type (;0;) (func))
  (type (;1;) (func (result i32)))
  (type (;2;) (func (result externref)))
  (type (;3;) (func (param i32)))
  (type (;4;) (func (param i32 i32) (result i32)))
  (type (;5;) (func (param i32 i32 i32 i32) (result i32)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;0;) (type 0)))
  (func $__wbindgen_realloc (;1;) (type 5) (param i32 i32 i32 i32) (result i32))
  (func $__wbindgen_malloc (;2;) (type 4) (param i32 i32) (result i32))
  (func $__wbindgen_exn_store (;3;) (type 3) (param i32))
  (func $get_media_source (;4;) (type 1) (result i32))
  (func $__externref_table_alloc (;5;) (type 1) (result i32))
  (func $"get_url externref shim" (;6;) (type 2) (result externref))
  (table (;0;) 128 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "get_url" (func $"get_url externref shim"))
  (export "get_media_source" (func $get_media_source))
  (export "__wbindgen_exn_store" (func $__wbindgen_exn_store))
  (export "__externref_table_alloc" (func $__externref_table_alloc))
  (export "__wbindgen_export_2" (table 0))
  (export "__wbindgen_malloc" (func $__wbindgen_malloc))
  (export "__wbindgen_realloc" (func $__wbindgen_realloc))
  (export "__wbindgen_start" (func 0))
  (@custom "target_features" (after code) "\04+\0amultivalue+\0fmutable-globals+\0freference-types+\08sign-ext")
)

