mod outputs_its_running_2_tests_feature;
mod outputs_no_error_feature;
mod outputs_no_information_about_the_skipped_test_1_feature;
mod outputs_no_information_about_the_skipped_test_2_feature;
mod outputs_the_assembly_test_summary_feature;
mod returns_success_feature;
