pub enum TestMode {
    Default,
    Deno,
    Node,
    BrowserDefault,
    BrowserChrome,
    BrowserEdge,
    BrowserFirefox,
    BrowserSafari,
    DedicatedWorkerDefault,
    DedicatedWorkerChrome,
    DedicatedWorkerEdge,
    DedicatedWorkerFirefox,
    DedicatedWorkerSafari,
}
