mod outputs_its_running_1_test_feature;
mod outputs_no_error_feature;
mod outputs_no_information_about_test_1_feature;
mod outputs_the_assembly_test_summary_feature;
mod outputs_the_successful_test_2_standard_output_feature;
mod outputs_the_successful_test_2_summary_feature;
mod returns_success_feature;
